stages:
  data_preprocessing:
    cmd: python src/stage_01_data_preprocess.py
    deps:
    - src/stage_01_data_preprocess.py
    - src/utils
    - data/data.xml
    outs:
    -   artifacts/prepared

  featurization:
    cmd: python src/stage_02_featurization.py
    deps:
    - src/stage_02_featurization.py
    - src/utils
    - artifacts/prepared
    outs:
    -   artifacts/features  

  training:
    cmd: python src/stage_03_train.py
    deps:
    - src/stage_03_train.py
    - src/utils
    - artifacts/features/train.pkl
    outs:
    -   artifacts/model/model.pkl   

  evaluation:
    cmd: python src/stage_04_evaluate.py
    deps:
    - src/stage_04_evaluate.py
    - src/utils
    - artifacts/features/test.pkl
    - artifacts/model/model.pkl
    metrics:
    - scores.json:
        cache: false
    plots:
    - prc.json:
        cache: false
        x: recall
        y: precision
    - roc.json:
        cache: false
        x: fpr
        y: tpr    
